#!/bin/bash
# vim: set sw=4 et sts=4 tw=80 :
# Copyright 2009 Ali Polatel <polatel@googlemail.com>
# Distributed under the terms of the GNU General Public License v2

# Convert an mp3 file to an ogg file keeping tag information.
# This example demonstrates the usage of -E/--export.

# additional options to pass to oggenc
oggenc_opts="-q 4"

if [[ 1 > $# ]]; then
    echo "usage: $(basename ${0}) file.mp3" >&2
    exit 1
else
    fmp3="${1}"
    fogg="${1/.mp3/.ogg}"
    if [[ "${fmp3}" == "${fogg}" ]]; then
        echo "invalid file (make sure file's extension is mp3)" >&2
        exit 1
    fi
fi

lame="$(type -P lame 2>/dev/null)"
if [[ -z "${lame}" ]]; then
    echo "lame not found in PATH" >&2
    exit 1
fi
oggenc="$(type -P oggenc 2>/dev/null)"
if [[ -z "${oggenc}" ]]; then
    echo "oggenc not found in PATH" >&2
    exit 1
fi

echo "${fmp3} -> ${fogg}" >&2
eval `envtag -E "${fmp3}"`
lame --decode "${fmp3}" - | oggenc "${oggenc_opts}" -o "${fogg}" -
envtag -v -s "${fogg}"
